let json = {
  "words" :
  {
    "start" :
    [
      "{genre} where you {action} {things}",
      "{genre} where you {adverb} {action} {things}",
      "{genre} where you can {action} {things}",
      "{genre} where you can {adverb} {action} {things}",
      "{genre} which forces you to {action} {things}",
      "{genre} which forces you to {adverb} {action} {things}",
      "{genre} which invites you to {action} {things}",
      "{genre} which invites you to {adverb} {action} {things}",
      "{genre} which questions the nature of {things}",
      "{genre} where {things} is the main focus",
      "{genre} which makes you {emotion} {things}",
      "a cross between {genre} and {genre} in which you {action} {things}",
      "a cross between {genre} and {genre} in which you {adverb} {action} {things}",
      "{genre} that's also {genre} that sees you {action} {things}",
      "{genre} that's also {genre} that sees you {adverb} {action} {things}"
    ],
    "end" : [
      ".",
      " {adverb}.",
      " but no-one cares.",
      " for no real point.",
      " to make money.",
      ", {things} not included.",
      " with {things}.",
      " thanks to {things}.",
      " for {things}.",
      " to {action} {things}.",
      " to {adverb} {action} {things}.",
      " {adverb}.",
      " and make {adjective} decisions.",
      " {reason}.",
      ", all {reason}.",
      " and it's all {reason}.",
      " but it gets weirder.",
      " but it's a metaphor about {things}.",
      " and it's really {adjective}.",
      ", but it's {adjective}.",
      ", or so you think.",
      ", but there's a shocking twist.",
      " but it's all in your head.",
      " and you {emotion} every minute of it.",
      " and you can't help but {emotion} it.",
      " and there are microtransactions.",
      " and it makes you reflect on {things}.",
      " and it makes you think about {things}.",
      " but it's secretly controlled by {things}.",
      " and you can {action} your house.",
      " and you can {adverb} {action} your house.",
      " and you can {action} your life.",
      " and you can {adverb} {action} your own life.",
      ", inspired by {inspiration}.",
      " - based on {inspiration}.",
      " and borrows elements from {inspiration}.",
      ", featuring Dante from the Devil May Cry series!",
      " and it's grindy as hell.",
      " and later introduces elements of {things}.",
      " and early on you're given {things} that you can {action}.",
      " with the addition of {things}.",
      " and there's a day/night cycle.",
      " with the power of {things}.",
      " and it includes {mechanic}.",
      " with {mechanic}.",
      " and it makes use of {mechanic}.",
      " in {location}.",
      " and it all takes place in {location}."
    ],
    "grammar" : {
      "genre" : [
        "a first person shooter",
        "a third person shooter",
        "a JRPG",
        "a god game",
        "an RPG",
        "an MMORPG",
        "an action game",
        "an action adventure",
        "a collectathon",
        "a platformer",
        "a free to play game",
        "a racing game",
        "a driving game",
        "a mobile game",
        "a visual novel",
        "a point and click",
        "a loot shooter",
        "a battle royale",
        "a flash game",
        "a rhythm game",
        "a browser game",
        "a casual game",
        "a puzzle game",
        "a simulator game",
        "a metroidvania",
        "a grand strategy game",
        "a real-time strategy",
        "a turn-based strategy",
        "a 4X strategy",
        "a fighting game",
        "a beat-em up",
        "a shoot-em up",
        "an open-world game",
        "a board game",
        "a roguelike",
        "a souls-like",
        "a student project",
        "a clicker game",
        "a game by Hideo Kojima",
        "a game by Peter Molyneaux",
        "a game by Sid Meier",
        "an indie game"
      ],
      "action" : [
        "gamify",
        "procedurally generate",
        "control",
        "implement",
        "exploit",
        "protect",
        "destroy",
        "tame",
        "hijack",
        "embrace",
        "disregard",
        "kill",
        "edit",
        "evade",
        "simulate",
        "observe",
        "micro-manage",
        "ruin",
        "improve",
        "rebel against",
        "fight with",
        "wrestle with",
        "investigate",
        "uncover",
        "discover",
        "explore",
        "hack",
        "analyse",
        "criticise",
        "befriend",
        "argue with",
        "boycott",
        "invest in",
        "debate",
        "construct",
        "research",
        "become haunted by",
        "become angry about",
        "customise",
        "modify",
        "generate",
        "defeat",
        "manage",
        "wage war against",
        "weaponise",
        "sell",
        "reinvent",
        "create",
        "undermine",
        "break down",
        "regulate",
        "contemplate",
        "resurrect",
        "defy",
        "question",
        "interrogate",
        "plagiarise",
        "steal"
      ],
      "things" : [
        "communism",
        "capitalism",
        "post-modernism",
        "politics",
        "telemarketers",
        "nightmares",
        "existential dread",
        "anxiety",
        "depression",
        "people",
        "the masses",
        "eldritch horrors",
        "schools",
        "the economy",
        "disappointment",
        "the free market",
        "yourself",
        "marketing",
        "Christianity",
        "the environment",
        "climate change",
        "agriculture",
        "history",
        "authority",
        "cats",
        "dogs",
        "horses",
        "birds",
        "serial killers",
        "trains",
        "cars",
        "civilisation",
        "clothing",
        "the flat earth movement",
        "Scientology",
        "terrorism",
        "the Titanic",
        "the Earth",
        "the Earth's resources",
        "the Moon",
        "the Sun",
        "Mars",
        "heaven",
        "hell",
        "the underworld",
        "the United States",
        "the merchant navy",
        "Europe",
        "Africa",
        "Asia",
        "Japan",
        "China",
        "France",
        "Italy",
        "addiction",
        "Russia",
        "skeletons",
        "giant rats",
        "employment",
        "mathematics",
        "physics",
        "philosophy",
        "atheism",
        "happiness",
        "sadness",
        "loneliness",
        "clouds",
        "video games",
        "progress",
        "the President of the United States of America",
        "the internet",
        "the military",
        "guns",
        "robots",
        "the mafia",
        "plague",
        "witchcraft",
        "magic",
        "Hideo Kojima",
        "Todd Howard",
        "Nazi Germany",
        "Soviet Russia",
        "the government",
        "the power of friendship",
        "puns",
        "anything",
        "everything",
        "the entirety of western civilisation",
        "your house",
        "your family",
        "God",
        "aliens",
        "zombies",
        "vampires",
        "werewolves"
      ],
      "adjective" : [
        "excellent",
        "good",
        "bad",
        "terrible",
        "interesting",
        "curious",
        "questionable",
        "irrational",
        "outrageous",
        "commendable",
        "hard",
        "boring",
        "dull",
        "invigorating",
        "exciting",
        "harrowing",
        "existential",
        "dreadful"
      ],
      "emotion" : [
        "love",
        "hate",
        "loathe",
        "enjoy",
        "doubt",
        "detest",
        "hallucinate",
        "imagine",
        "question",
        "overthink"
      ],
      "adverb" : [
        "quickly",
        "beautifully",
        "easily",
        "smoothly",
        "cruelly",
        "badly",
        "slowly",
        "poorly",
        "skilfully",
        "deftly",
        "silently",
        "quietly",
        "stealthily",
        "confidently",
        "reluctantly",
        "unknowingly",
        "unwittingly",
        "horrifically",
        "cautiously",
        "ironically",
        "unironically",
        "accidentally",
        "deliberately",
        "competitively",
        "indifferently",
        "angrily"
      ],
      "inspiration" : [
        "The Lord of the Rings",
        "Star Wars",
        "The Matrix",
        "eastern philosophy",
        "eastern religion",
        "the wild west",
        "capitalist excess",
        "the Sengoku period",
        "The Iliad",
        "Dante's Inferno",
        "Greek mythology",
        "World War 1",
        "World War 2",
        "the war on drugs",
        "a true story",
        "historical events"
      ],
      "mechanic" : [
        "loot boxes",
        "a dynamic weather system",
        "a day/night cycle",
        "quick time events",
        "stealth mechanics",
        "a crafting system",
        "dynamic quests",
        "precision platforming",
        "wall running",
        "perma-death",
        "RPG mechanics",
        "online leaderboards",
        "a complex story",
        "long cutscenes",
        "love polygons",
        "branching questlines",
        "difficult moral choices",
        "difficult decisions with lasting consequences"
      ],
      "location": [
        "the future",
        "the near future",
        "the distant future",
        "the past",
        "the distant past",
        "another world",
        "an alternate universe",
        "an alternate timeline",
        "a fantasy world",
        "a dystopian world",
        "a post-apocalyptic world",
        "the modern world",
        "Russia",
        "the United States of America",
        "Japan",
        "Mexico",
        "heaven",
        "the underworld",
        "hell",
        "outer space",
        "a Martian colony",
        "2D",
        "3D",
        "virtual reality",
        "the cloud",
        "summer",
        "winter",
        "deep winter"
      ],
      "reason" : [
        "for personal gain",
        "to make friends",
        "to collect treasure",
        "to better understand society",
        "to get higher scores that your friends",
        "for research purposes",
        "for your entertainment"
      ]
    }
  }
};

let start = json['words']['start'];
let end = json['words']['end'];
let grammar = json['words']['grammar'];
let idea = document.getElementById('idea');

function getRandomInt(min, max) {
  return Math.floor(Math.random() * Math.floor(max)) + min;
}

function replaceStr(arr, str) {
  let rno = getRandomInt(0, arr.length);
  return arr[rno];
}

function generate() {
  let chosenStart = getRandomInt(0, start.length);
  let chosenEnd = getRandomInt(0, end.length);
  let regex = /[{][a-z]+[}]/gm;
  let lastGenre = '';

  // Built sentence structure
  let currentIdea = start[chosenStart] + end[chosenEnd];

  // Place all matches in an array
  let placeholders = [...currentIdea.matchAll(regex)];

  // Replace each match one at a time
  for (const p of placeholders) {
    var block = p[0].substr(1, p[0].length - 2);

    var r = new RegExp("[{][" + block + "]+[}]");
    var replace = replaceStr(grammar[block], currentIdea);

    if (block === 'genre') {
      // Try to find a new genre that doesn't match the last
      while(replace === lastGenre) {
        replace = replaceStr(grammar[block], currentIdea);
      }
      lastGenre = replace;
    }
    currentIdea = currentIdea.replace(r, replace);
  }
  idea.innerHTML = currentIdea;
  console.log(currentIdea);
}
